---
- name: Create VM on RHV
  hosts: localhost
  connection: local
  gather_facts: false

  vars_files:
    - rhv_vars.yml
    - passwords.yml

  pre_tasks:
    - name: Login to oVirt
      ovirt_auth:
        hostname: "{{ engine_fqdn }}"
        username: "{{ engine_user }}"
        password: "{{ engine_password }}"
        ca_file: "{{ engine_cafile | default(omit) }}"
        insecure: "{{ rhvm_insecure | default(true) }}"
      tags:
        - always

  vars:
    datacenter: Default
    cluster: Default
    template: Template_OpenShift_311
    vm_memory: 16GiB
    vm_name: test-vm01


  tasks:
  - name: Create and run VM from template
    ovirt_vms:
      auth: "{{ ovirt_auth }}"
      name: "{{ vm_name }}"
      template: "{{ template }}"
      cluster: "{{ cluster }}"
      memory: "{{vm_memory}}"
      nics:
        - name: ocp_pdn_eps_ips
      high_availability: true
      state: present
      wait: yes
#      disks:
#        - size: 40GiB
#          name: "{{ vm_name }}_Disk2"
#          storage_domain: rhvdata09
#          interface: virtio

  post_tasks:
    - name: Logout from oVirt
      ovirt_auth:
        state: absent
        ovirt_auth: "{{ ovirt_auth }}"
      tags:
       - always
